In [2]:
import numpy as np
np.random.random(4)

array([0.46341486, 0.24366094, 0.53494835, 0.89287176])

In [3]:
np.random.seed(1)
np.random.randint(low = 1, high = 10, size = 50)

array([6, 9, 6, 1, 1, 2, 8, 7, 3, 5, 6, 3, 5, 3, 5, 8, 8, 2, 8, 1, 7, 8,
       7, 2, 1, 2, 9, 9, 4, 9, 8, 4, 7, 6, 2, 4, 5, 9, 2, 5, 1, 4, 3, 1,
       5, 3, 8, 8, 9, 7])

In [4]:
np.random.seed(0)
np.random.randint(10, size = 5)

array([5, 0, 3, 3, 7])

In [5]:
np.random.seed(0)
np.random.random()

0.5488135039273248

In [6]:
np.random.seed(0)
np.random.random()

0.5488135039273248

In [7]:
np.random.seed(74)
np.random.randint(low = 0, high = 100, size = 5)

array([30, 91,  9, 73, 62])

In [8]:
np.random.seed(74)
np.random.randint(low = 0, high = 100, size = 5)

array([30, 91,  9, 73, 62])

In [9]:
np.random.seed(74)
np.random.randint(low = 0, high = 100, size = 4)

array([30, 91,  9, 73])

In [10]:
np.random.seed(75)
np.random.randint(low = 0, high = 100, size = 5)

array([19, 81,  8, 64, 26])

In [11]:
np.random.seed(0)
np.random.choice(a = [1,2,3,4,5,6], size = 5)

array([5, 6, 1, 4, 4])

In [12]:
np.random.seed(0)
np.random.randint(99, size = 5)

array([44, 47, 64, 67, 67])

In [13]:
np.random.seed(42)
np.random.randint(99, size = 5)

array([51, 92, 14, 71, 60])

In [14]:
np.random.seed(1)
np.random.randint(99, size = 5)

array([37, 12, 72,  9, 75])

In [15]:
np.random.seed(1)
np.random.normal(loc = 0, scale = 1, size = (3,3))

array([[ 1.62434536, -0.61175641, -0.52817175],
       [-1.07296862,  0.86540763, -2.3015387 ],
       [ 1.74481176, -0.7612069 ,  0.3190391 ]])

In [16]:
np.random.seed(1)
np.random.randn(3, 3)

array([[ 1.62434536, -0.61175641, -0.52817175],
       [-1.07296862,  0.86540763, -2.3015387 ],
       [ 1.74481176, -0.7612069 ,  0.3190391 ]])

In [28]:
np.random.normal(1)

-0.10061917721292124

In [29]:
np.random.normal(size = 1, loc = 0, scale = 1)

array([1.14472371])

In [30]:
np.random.normal(5)

5.901590720592796

In [31]:
np.random.normal(size = 5, loc = 0, scale = 1)

array([ 0.50249434,  0.90085595, -0.68372786, -0.12289023, -0.93576943])

In [32]:
np.random.normal(size = 1, loc = 0, scale = 5)

array([-1.3394404])

In [36]:
np.random.seed(42)
np.random.normal(size = (2, 3))

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696]])

In [37]:
np.random.seed(42)
np.random.normal(size = 1000, loc = 50)

array([50.49671415, 49.8617357 , 50.64768854, 51.52302986, 49.76584663,
       49.76586304, 51.57921282, 50.76743473, 49.53052561, 50.54256004,
       49.53658231, 49.53427025, 50.24196227, 48.08671976, 48.27508217,
       49.43771247, 48.98716888, 50.31424733, 49.09197592, 48.5876963 ,
       51.46564877, 49.7742237 , 50.0675282 , 48.57525181, 49.45561728,
       50.11092259, 48.84900642, 50.37569802, 49.39936131, 49.70830625,
       49.39829339, 51.85227818, 49.98650278, 48.94228907, 50.82254491,
       48.77915635, 50.2088636 , 48.04032988, 48.67181395, 50.19686124,
       50.73846658, 50.17136828, 49.88435172, 49.6988963 , 48.52147801,
       49.28015579, 49.53936123, 51.05712223, 50.34361829, 48.23695984,
       50.32408397, 49.61491772, 49.323078  , 50.61167629, 51.03099952,
       50.93128012, 49.16078248, 49.69078762, 50.33126343, 50.97554513,
       49.52082576, 49.81434102, 48.89366503, 48.80379338, 50.81252582,
       51.35624003, 49.92798988, 51.0035329 , 50.36163603, 49.35

In [38]:
np.random.seed(42)
np.random.normal(size = 1000, scale = 100)

array([ 4.96714153e+01, -1.38264301e+01,  6.47688538e+01,  1.52302986e+02,
       -2.34153375e+01, -2.34136957e+01,  1.57921282e+02,  7.67434729e+01,
       -4.69474386e+01,  5.42560044e+01, -4.63417693e+01, -4.65729754e+01,
        2.41962272e+01, -1.91328024e+02, -1.72491783e+02, -5.62287529e+01,
       -1.01283112e+02,  3.14247333e+01, -9.08024076e+01, -1.41230370e+02,
        1.46564877e+02, -2.25776300e+01,  6.75282047e+00, -1.42474819e+02,
       -5.44382725e+01,  1.10922590e+01, -1.15099358e+02,  3.75698018e+01,
       -6.00638690e+01, -2.91693750e+01, -6.01706612e+01,  1.85227818e+02,
       -1.34972247e+00, -1.05771093e+02,  8.22544912e+01, -1.22084365e+02,
        2.08863595e+01, -1.95967012e+02, -1.32818605e+02,  1.96861236e+01,
        7.38466580e+01,  1.71368281e+01, -1.15648282e+01, -3.01103696e+01,
       -1.47852199e+02, -7.19844208e+01, -4.60638771e+01,  1.05712223e+02,
        3.43618290e+01, -1.76304016e+02,  3.24083969e+01, -3.85082280e+01,
       -6.76922000e+01,  

In [39]:
np.random.seed(42)
np.random.normal(size = 1000, scale = 100).std()

97.87262077473541